### ISSUE TITLE
Variables in test steps

### ISSUE THREAD

**Issue by ajsteenkamp** [vitalets/playwright-magic-steps#2]
I include variables in my test.step to make it even more intuitive and easy to follow but how would you something like the below using magic steps?

```
await test.step(`Enter search term '${searchTerm}' in to search bar`, async () => {
```

**Comment by vitalets** [comment]
Yes, you can use variables in step text like in regular template literals, e.g.:
```
const searchTerm = 'foo';
// step: Enter search term '${searchTerm}' in to search bar
```
Report:
<img width="60%" src="https://github.com/user-attachments/assets/da5f04b2-18ed-4ace-91c8-db9f4bc3c2c3">

Updated README.
