### ISSUE TITLE
Any chance allure will be supported?

### ISSUE THREAD

**Issue by ohlori** [vitalets/playwright-magic-steps#4]
Currently using allure-playwright as a reporter. Unfortunately, all the steps get nested.
![image](https://github.com/user-attachments/assets/d292c13a-5518-4065-a692-48e1f1e5e81a)

Everything good with playwright default html reporter. 
![image](https://github.com/user-attachments/assets/9750347a-74a1-40a7-ac46-1dffea047dd0)

**Comment by vitalets** [comment]
Could you show the test code?
I've ran the [example](https://github.com/vitalets/playwright-magic-steps/tree/main/example) with allure-playwright and it produced all steps on the same level:
<img width="50%" src="https://github.com/user-attachments/assets/6bd187b6-5089-42ca-9c0e-bc49acaf80a1">

**Comment by ohlori** [comment]
Here's how i implemented it.
![image](https://github.com/user-attachments/assets/910f6ab5-bb4a-4568-84e1-e767a5faf570)

**Comment by ohlori** [comment]
Here's how I used  it
![image](https://github.com/user-attachments/assets/01468dae-62e9-4058-8625-ff86b630331f)

**Comment by vitalets** [comment]
I think there should be `await` before `waitUntilNoSpinner(page)`.

**Comment by ohlori** [comment]
You were rightttttttt 🤦‍♀️ sorry for the trouble!

This is amazing! It gives the python vibes! Loving and recommending this!
