### ISSUE TITLE
[QUESTION] Could there be a nested-step identifier to override the workspace settings?

### ISSUE THREAD

**Issue by ohlori** [vitalets/playwright-magic-steps#6]
Hello @vitalets ! 

As the title itself, I'm wondering if it's possible. There might be instances where some other developers might overwrite the indentations of the test steps due to individual workspace settings/extensions.

Example: When `editor.formatOnSave` is `true`
![nested-step](https://github.com/user-attachments/assets/e40ea846-3469-424e-b6e1-96a37ce947b0)

I would like to propose to have something like `// nstep: ${title}` to indicate it being nested on top of the previous `step`/`nstep`?

**Comment by vitalets** [comment]
Hey @ohlori 

Is your intention to have 3 last steps nested into `step: Populating ...`?
If yes, you can do the following - wrap nested steps into anonymous `{}` block. Prettier will format them with indent.
Example:
```ts
test('Check home page', async ({ page }) => {
  // step: Open home page
  await page.goto('https://playwright.dev');
  {
    // step: Click 'Get started' link
    await page.getByRole('link', { name: 'Get started' }).click();
    // step: Check page title
    await expect(page).toHaveTitle('Installation | Playwright');
  }
});
```

I like that nested steps are kept indented, compared to `nstep` solution.
Let me know, does it work for your?
I think I'll add it to docs, as it's very valid use-case.
